name: Build and Test in Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Amethyst Ubuntu Dependencies
      run: sudo apt-get install gcc pkg-config openssl libasound2-dev cmake build-essential python3 libfreetype6-dev libexpat1-dev libxcb-composite0-dev libssl-dev libx11-dev
    - name: Update Rust
      run: rustup update
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
